# Generated by Django 3.1.2 on 2020-10-16 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_auto_20201016_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='email',
            field=models.EmailField(help_text='Enter email address', max_length=200),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ManyToManyField(to='admin_page.Link')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_page.userlist')),
            ],
        ),
    ]
