# Generated by Django 3.1.2 on 2020-10-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0003_auto_20201016_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='data',
            name='category',
            field=models.ManyToManyField(to='admin_page.CategoryList'),
        ),
        migrations.AddField(
            model_name='data',
            name='title',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
        migrations.RemoveField(
            model_name='data',
            name='link',
        ),
        migrations.AddField(
            model_name='data',
            name='link',
            field=models.TextField(default='DEFAULT', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
