# Generated by Django 3.1.2 on 2020-10-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0004_auto_20201016_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Enter email address', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.EmailField(default='DEFAULT', max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='email',
            field=models.EmailField(help_text='Enter email address', max_length=200, verbose_name='Email'),
        ),
    ]
