# Generated by Django 3.1.2 on 2020-10-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0005_auto_20201019_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(choices=[('1', 'SD Kelas 1'), ('2', 'SD Kelas 2'), ('3', 'SD Kelas 3'), ('4', 'SD Kelas 4')], default='1', help_text='Kelas', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelajaran', models.CharField(help_text='Pelajaran', max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='CategoryList',
            new_name='Kategori',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['user']},
        ),
        migrations.RenameField(
            model_name='data',
            old_name='title',
            new_name='judul',
        ),
        migrations.RemoveField(
            model_name='data',
            name='category',
        ),
        migrations.AddField(
            model_name='data',
            name='kategori',
            field=models.ManyToManyField(to='admin_page.Kategori'),
        ),
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='user',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
        migrations.AddField(
            model_name='data',
            name='kelas',
            field=models.ManyToManyField(to='admin_page.Kelas'),
        ),
        migrations.AddField(
            model_name='data',
            name='pelajaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_page.pelajaran'),
        ),
    ]
