# Generated by Django 3.1.2 on 2020-10-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0007_auto_20201019_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ['category']},
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={'ordering': ['kelas']},
        ),
        migrations.AlterModelOptions(
            name='pelajaran',
            options={'ordering': ['pelajaran']},
        ),
    ]
