# Generated by Django 3.1.2 on 2020-11-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0008_auto_20201021_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.DeleteModel(
            name='Kelas',
        ),
        migrations.DeleteModel(
            name='Pelajaran',
        ),
    ]
